// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable, dead_code, unnecessary_cast
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

import 'dart:io';

import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';
import 'package:amap_location_fluttify/src/android/android.export.g.dart';

import 'package:foundation_fluttify/foundation_fluttify.dart';
import 'package:core_location_fluttify/core_location_fluttify.dart';
import 'package:amap_core_fluttify/amap_core_fluttify.dart';

// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import
// type check
@optionalTypeArgs
Future<bool> AmapLocationFluttifyAndroidIs<T>(dynamic __this__) async {
  final typeName = T.toString();
  if (RegExp(r'^(List<)?(String|int|double)(>)?|(Map<String,(String|int|double)>)$').hasMatch(typeName)) {
    return __this__ is T;
  }
  else if (T == com_amap_api_location_AMapLocationClient) {
    final result = await kAmapLocationFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_location_AMapLocationClient', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_location_APSService) {
    final result = await kAmapLocationFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_location_APSService', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_location_DPoint) {
    final result = await kAmapLocationFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_location_DPoint', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_location_CoordinateConverter) {
    final result = await kAmapLocationFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_location_CoordinateConverter', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_location_CoordUtil) {
    final result = await kAmapLocationFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_location_CoordUtil', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_location_UmidtokenInfo) {
    final result = await kAmapLocationFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_location_UmidtokenInfo', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_location_AMapLocation) {
    final result = await kAmapLocationFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_location_AMapLocation', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_location_AMapLocationClientOption) {
    final result = await kAmapLocationFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_location_AMapLocationClientOption', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_location_AMapLocationQualityReport) {
    final result = await kAmapLocationFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_location_AMapLocationQualityReport', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_fence_DistrictItem) {
    final result = await kAmapLocationFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_fence_DistrictItem', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_fence_GeoFenceClient) {
    final result = await kAmapLocationFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_fence_GeoFenceClient', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_fence_GeoFence) {
    final result = await kAmapLocationFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_fence_GeoFence', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_fence_PoiItem) {
    final result = await kAmapLocationFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_fence_PoiItem', {'__this__': __this__});
    return result;
  } else if (T == android_content_Context) {
    final result = await kAmapLocationFluttifyChannel.invokeMethod('RefClass::isKindOfandroid_content_Context', {'__this__': __this__});
    return result;
  } else if (T == android_content_Intent) {
    final result = await kAmapLocationFluttifyChannel.invokeMethod('RefClass::isKindOfandroid_content_Intent', {'__this__': __this__});
    return result;
  } else if (T == android_content_ContentProvider) {
    final result = await kAmapLocationFluttifyChannel.invokeMethod('RefClass::isKindOfandroid_content_ContentProvider', {'__this__': __this__});
    return result;
  } else if (T == android_app_Application) {
    final result = await kAmapLocationFluttifyChannel.invokeMethod('RefClass::isKindOfandroid_app_Application', {'__this__': __this__});
    return result;
  } else if (T == android_app_Notification) {
    final result = await kAmapLocationFluttifyChannel.invokeMethod('RefClass::isKindOfandroid_app_Notification', {'__this__': __this__});
    return result;
  } else if (T == android_app_Activity) {
    final result = await kAmapLocationFluttifyChannel.invokeMethod('RefClass::isKindOfandroid_app_Activity', {'__this__': __this__});
    return result;
  } else if (T == android_app_PendingIntent) {
    final result = await kAmapLocationFluttifyChannel.invokeMethod('RefClass::isKindOfandroid_app_PendingIntent', {'__this__': __this__});
    return result;
  } else if (T == android_os_Bundle) {
    final result = await kAmapLocationFluttifyChannel.invokeMethod('RefClass::isKindOfandroid_os_Bundle', {'__this__': __this__});
    return result;
  } else if (T == android_os_Binder) {
    final result = await kAmapLocationFluttifyChannel.invokeMethod('RefClass::isKindOfandroid_os_Binder', {'__this__': __this__});
    return result;
  } else if (T == android_view_View) {
    final result = await kAmapLocationFluttifyChannel.invokeMethod('RefClass::isKindOfandroid_view_View', {'__this__': __this__});
    return result;
  } else if (T == android_view_SurfaceView) {
    final result = await kAmapLocationFluttifyChannel.invokeMethod('RefClass::isKindOfandroid_view_SurfaceView', {'__this__': __this__});
    return result;
  } else if (T == android_view_ViewGroup) {
    final result = await kAmapLocationFluttifyChannel.invokeMethod('RefClass::isKindOfandroid_view_ViewGroup', {'__this__': __this__});
    return result;
  } else if (T == android_graphics_Point) {
    final result = await kAmapLocationFluttifyChannel.invokeMethod('RefClass::isKindOfandroid_graphics_Point', {'__this__': __this__});
    return result;
  } else if (T == android_graphics_PointF) {
    final result = await kAmapLocationFluttifyChannel.invokeMethod('RefClass::isKindOfandroid_graphics_PointF', {'__this__': __this__});
    return result;
  } else if (T == android_graphics_Bitmap) {
    final result = await kAmapLocationFluttifyChannel.invokeMethod('RefClass::isKindOfandroid_graphics_Bitmap', {'__this__': __this__});
    return result;
  } else if (T == android_widget_ImageView) {
    final result = await kAmapLocationFluttifyChannel.invokeMethod('RefClass::isKindOfandroid_widget_ImageView', {'__this__': __this__});
    return result;
  } else if (T == java_io_File) {
    final result = await kAmapLocationFluttifyChannel.invokeMethod('RefClass::isKindOfjava_io_File', {'__this__': __this__});
    return result;
  } else if (T == android_location_Location) {
    final result = await kAmapLocationFluttifyChannel.invokeMethod('RefClass::isKindOfandroid_location_Location', {'__this__': __this__});
    return result;
  } else if (T == android_view_MotionEvent) {
    final result = await kAmapLocationFluttifyChannel.invokeMethod('RefClass::isKindOfandroid_view_MotionEvent', {'__this__': __this__});
    return result;
  } else if (T == android_graphics_drawable_Drawable) {
    final result = await kAmapLocationFluttifyChannel.invokeMethod('RefClass::isKindOfandroid_graphics_drawable_Drawable', {'__this__': __this__});
    return result;
  } else if (T == android_widget_FrameLayout) {
    final result = await kAmapLocationFluttifyChannel.invokeMethod('RefClass::isKindOfandroid_widget_FrameLayout', {'__this__': __this__});
    return result;
  } else if (T == android_widget_TextView) {
    final result = await kAmapLocationFluttifyChannel.invokeMethod('RefClass::isKindOfandroid_widget_TextView', {'__this__': __this__});
    return result;
  } else if (T == android_widget_LinearLayout) {
    final result = await kAmapLocationFluttifyChannel.invokeMethod('RefClass::isKindOfandroid_widget_LinearLayout', {'__this__': __this__});
    return result;
  } else if (T == android_widget_RelativeLayout) {
    final result = await kAmapLocationFluttifyChannel.invokeMethod('RefClass::isKindOfandroid_widget_RelativeLayout', {'__this__': __this__});
    return result;
  } else if (T == android_os_Parcelable) {
    final result = await kAmapLocationFluttifyChannel.invokeMethod('RefClass::isKindOfandroid_os_Parcelable', {'__this__': __this__});
    return result;
  } else if (T == android_util_Pair) {
    final result = await kAmapLocationFluttifyChannel.invokeMethod('RefClass::isKindOfandroid_util_Pair', {'__this__': __this__});
    return result;
  }
  else {
    return false;
  }
}

// type cast
// 给一个可选的泛型, 如果没有指定泛型就返回dynamic
@optionalTypeArgs
T AmapLocationFluttifyAndroidAs<T>(dynamic __this__) {
  final typeName = T.toString();

  if (__this__ == null) {
    return null;
  } else if (RegExp(r'^(List<)?(String|int|double)(>)?|(Map<String,(String|int|double)>)$').hasMatch(typeName)) {
    return __this__ as T;
  }
  else if (T == com_amap_api_location_AMapLocationClient) {
    return (com_amap_api_location_AMapLocationClient()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_location_APSService) {
    return (com_amap_api_location_APSService()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_location_DPoint) {
    return (com_amap_api_location_DPoint()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_location_CoordinateConverter) {
    return (com_amap_api_location_CoordinateConverter()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_location_CoordUtil) {
    return (com_amap_api_location_CoordUtil()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_location_UmidtokenInfo) {
    return (com_amap_api_location_UmidtokenInfo()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_location_AMapLocation) {
    return (com_amap_api_location_AMapLocation()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_location_AMapLocationClientOption) {
    return (com_amap_api_location_AMapLocationClientOption()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_location_AMapLocationQualityReport) {
    return (com_amap_api_location_AMapLocationQualityReport()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_fence_DistrictItem) {
    return (com_amap_api_fence_DistrictItem()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_fence_GeoFenceClient) {
    return (com_amap_api_fence_GeoFenceClient()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_fence_GeoFence) {
    return (com_amap_api_fence_GeoFence()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_fence_PoiItem) {
    return (com_amap_api_fence_PoiItem()..refId = (__this__ as Ref).refId) as T;
  } else if (T == android_content_Context) {
    return (android_content_Context()..refId = (__this__ as Ref).refId) as T;
  } else if (T == android_content_Intent) {
    return (android_content_Intent()..refId = (__this__ as Ref).refId) as T;
  } else if (T == android_content_ContentProvider) {
    return (android_content_ContentProvider()..refId = (__this__ as Ref).refId) as T;
  } else if (T == android_app_Application) {
    return (android_app_Application()..refId = (__this__ as Ref).refId) as T;
  } else if (T == android_app_Notification) {
    return (android_app_Notification()..refId = (__this__ as Ref).refId) as T;
  } else if (T == android_app_Activity) {
    return (android_app_Activity()..refId = (__this__ as Ref).refId) as T;
  } else if (T == android_app_PendingIntent) {
    return (android_app_PendingIntent()..refId = (__this__ as Ref).refId) as T;
  } else if (T == android_os_Bundle) {
    return (android_os_Bundle()..refId = (__this__ as Ref).refId) as T;
  } else if (T == android_os_Binder) {
    return (android_os_Binder()..refId = (__this__ as Ref).refId) as T;
  } else if (T == android_view_View) {
    return (android_view_View()..refId = (__this__ as Ref).refId) as T;
  } else if (T == android_view_SurfaceView) {
    return (android_view_SurfaceView()..refId = (__this__ as Ref).refId) as T;
  } else if (T == android_view_ViewGroup) {
    return (android_view_ViewGroup()..refId = (__this__ as Ref).refId) as T;
  } else if (T == android_graphics_Point) {
    return (android_graphics_Point()..refId = (__this__ as Ref).refId) as T;
  } else if (T == android_graphics_PointF) {
    return (android_graphics_PointF()..refId = (__this__ as Ref).refId) as T;
  } else if (T == android_graphics_Bitmap) {
    return (android_graphics_Bitmap()..refId = (__this__ as Ref).refId) as T;
  } else if (T == android_widget_ImageView) {
    return (android_widget_ImageView()..refId = (__this__ as Ref).refId) as T;
  } else if (T == java_io_File) {
    return (java_io_File()..refId = (__this__ as Ref).refId) as T;
  } else if (T == android_location_Location) {
    return (android_location_Location()..refId = (__this__ as Ref).refId) as T;
  } else if (T == android_view_MotionEvent) {
    return (android_view_MotionEvent()..refId = (__this__ as Ref).refId) as T;
  } else if (T == android_graphics_drawable_Drawable) {
    return (android_graphics_drawable_Drawable()..refId = (__this__ as Ref).refId) as T;
  } else if (T == android_widget_FrameLayout) {
    return (android_widget_FrameLayout()..refId = (__this__ as Ref).refId) as T;
  } else if (T == android_widget_TextView) {
    return (android_widget_TextView()..refId = (__this__ as Ref).refId) as T;
  } else if (T == android_widget_LinearLayout) {
    return (android_widget_LinearLayout()..refId = (__this__ as Ref).refId) as T;
  } else if (T == android_widget_RelativeLayout) {
    return (android_widget_RelativeLayout()..refId = (__this__ as Ref).refId) as T;
  } else if (T == android_os_Parcelable) {
    return (android_os_Parcelable.subInstance()..refId = (__this__ as Ref).refId) as T;
  } else if (T == android_util_Pair) {
    return (android_util_Pair()..refId = (__this__ as Ref).refId) as T;
  }
  else if (AmapCoreFluttifyAndroidAs<T>(__this__) != null) {
    return AmapCoreFluttifyAndroidAs<T>(__this__);
  }
  else {
    return null;
  }
}